### ISSUE TITLE
Display time of day countdown timer

### ISSUE THREAD

**Issue by EclipseTech** [EclipseTech/FishingBuddy#1]
Display time of day countdown timer as optional part of `_timeOfDayPanel`

Initially display above or below panel, future enhancement needed to add more choice

**Comment by SOL4RIS** [comment]
Just a note, it might be a nice option to see the countdown superimposed over the day/night icon.

**Comment by EclipseTech** [comment]
v1.0.11 countdown timer is stable with options for top, middle, bottom alignments
