### ISSUE TITLE
Display catchable fish based on current achievements not updating correctly

### ISSUE THREAD

**Issue by MrMaddiman** [EclipseTech/FishingBuddy#17]
**Describe the bug**
The "(Optional) API token required Display catchable fish based on current achievements" feature does not work correctly on my installation of the plugin, it seems to update the optional saltwater and world class fisher achievements correctly, only listing the fish I'm missing when I have "ignore caught fish" toggled on, but any area specific fishing achievement seems to read as already completed despite there being fish left to catch in the list.
For example, I went to Sandswept isles to check out what fish were there, and nothing except the rares I still have to catch in the saltwater and world class fisher achievement came up, despite me never even having been to this area before. Once I toggle off "ignore caught fish" the whole list pops back up perfectly fine.
I tried generating a brand new API key with everything in it, and the same issue persists.

**To Reproduce**
All I have to do is enter the game and compare the list to the expected list from the achievements window and then toggle "ignore caught fish" on and off, so I'm horrified to think this bug applies specifically to my install.

**Expected behavior**
I expected the plugin to be able to read the info off the API, using my supplied API key, it apparently can, but for some reason only the two optional collections update properly.

![image](https://user-images.githubusercontent.com/103249241/162404075-192f0086-6018-4c69-abc6-6f44ea077e81.png)
![image](https://user-images.githubusercontent.com/103249241/162404189-c2bb2179-fc17-40d8-9530-d44e823d7275.png)
As you can see these two collections seem to work fine ^

![image](https://user-images.githubusercontent.com/103249241/162404641-24d859b4-7899-4fa3-b93c-747b49ae4135.png)
![image](https://user-images.githubusercontent.com/103249241/162404779-50ae89f5-8934-4c54-8237-1fe1702fe7cb.png)
Whereas this one does not. Except if I turn off the "ignore caught fish" feature.
![image](https://user-images.githubusercontent.com/103249241/162405164-0663eae5-a51d-4209-9523-fb43cfbe93a2.png)

Any help would be appreciated, I really like the plugin but this is the number one feature I wanted to use.

**Comment by EclipseTech** [comment]
Thanks! I'm definitely looking at this, although I don't have the ability to test. It is related to the fact that you have 0 progress on that particular achievement. For now catching 1 fish in the zone and letting the api have time to update, then switching maps, relogging, restarting module/blish, or cycling setting should refresh should start showing correctly.

**Comment by EclipseTech** [comment]
Try v1.0.3 and let me know if that fixes this (assuming you have 0 progression still on one achievement)

**Comment by EclipseTech** [comment]
Going to close this as fixed (comment if it's not)

**Comment by EclipseTech** [comment]
It wasn't fixed, but should be in v1.0.7

Turns out account achievements API doesn't count a 0 progress in account achievements.

Had to get one of my achievements done to get 0 progress on an Avid to see the bug
