### ISSUE TITLE
Fish Icons not showing or stacked - API not taken into account

### ISSUE THREAD

**Issue by oeGStefan** [EclipseTech/FishingBuddy#20]
**Describe the bug**
Fishing Buddy (fb) shows only one fish (or all of them stacked) and does not take API result into account. Shows fish, that has already been catched. Does not show all the uncatchables. While working, as changing options for rarity, grid layout and so on, are applied.

**To Reproduce**
Done settings reset, uninstalll, reinstall, multiple option combinations, changing and creating new API (all included), trying on 2nd account on 2nd PC, all the same.

**Expected behavior**
Show all fish of the region, added by the uncatchable ones, less the already caught ones.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: Always current one

**Additional context**
![Kaineng-BlishHUD-Fishing-Buddy](https://user-images.githubusercontent.com/83425226/164479944-5b522149-db4c-47ea-abaa-b878f23176dc.jpg)

Using Guild Wars 2 with German Language. Changing to English did not change the behavior.

**Comment by oeGStefan** [comment]
Yeah, that was Kaineng, but its the same with Saitung. See new Screenshot

[blishhud.20220421-160136.log](https://github.com/EclipseTech/FishingBuddy/files/8533562/blishhud.20220421-160136.log)

![Saitung-BlishHUD-Fishing-Buddy](https://user-images.githubusercontent.com/83425226/164521665-f491f777-4428-49d1-a561-99a385a14d30.jpg)

**Comment by EclipseTech** [comment]
Can you include logs?

**Comment by oeGStefan** [comment]
I did, above the screenshot.

**Comment by EclipseTech** [comment]
Sorry missed the logs.

I believe this is an issue with translation... I don't have a current fix for this.

Looks like when getting the achievement's fish names different translations change the item names. 

Since the API doesn't give info about fish, time of day, bait, fishing hole, etc. I have to map data using my created data `fish.json`. There is an enhancement to add fish item ids to the data I have. That would allow me to check via id instead of by name. Assuming the item id doesn't differ between language translations. https://github.com/EclipseTech/FishingBuddy/issues/5

Example of error from logs:
```
16:01:55.3926 | WARN  | Eclipse1807.BlishHUD.FishingBuddy.FishingBuddyModule | Missing fish from all fish list: Smaragd-Schnapper
16:01:55.4656 | WARN  | Eclipse1807.BlishHUD.FishingBuddy.FishingBuddyModule | Missing fish from all fish list: Bernsteinmakrele
16:01:55.5404 | WARN  | Eclipse1807.BlishHUD.FishingBuddy.FishingBuddyModule | Missing fish from all fish list: Blaue Goldmakrele
16:01:55.6009 | WARN  | Eclipse1807.BlishHUD.FishingBuddy.FishingBuddyModule | Missing fish from all fish list: Dickkopf-Makrele
16:01:55.6661 | WARN  | Eclipse1807.BlishHUD.FishingBuddy.FishingBuddyModule | Missing fish from all fish list: Blauflossen-Thunfisch
16:01:55.8050 | WARN  | Eclipse1807.BlishHUD.FishingBuddy.FishingBuddyModule | Missing fish from all fish list: Kaiserfisch
```

**Comment by oeGStefan** [comment]
Added the requested information in #5 ad created a new file to test with.
For additional input, I need updated requirements.

IG contact: Almachial.5493

**Comment by EclipseTech** [comment]
Thanks, I've almost gotten all the data setup to use item ids instead of name checks, which means it should show up proper in different languages.

**Comment by EclipseTech** [comment]
This should be fixed in v1.0.6

**Comment by oeGStefan** [comment]
So with Update 1.0.6 I can confirm, that it shows Icons for World Class Fish and Salt Water Fish, when activated in options.
But when I am in Kaineng,  I do not see a single fish in the list, while having the normal achievement done (all 21 caught) and having the avid achievement aavailable, with no fish caught yet. Any idea?

[blishhud.20220424-193655.log](https://github.com/EclipseTech/FishingBuddy/files/8550203/blishhud.20220424-193655.log)

**Comment by oeGStefan** [comment]
This changed with the first fish collected and the api refrehed in blish hud. So FB seems not to know, when I have done the first achievement and got the avid one activated but not yet started.
