### ISSUE TITLE
Include needed fish for specialization collection from End of Dragon

### ISSUE THREAD

**Issue by oeGStefan** [EclipseTech/FishingBuddy#21]
**Describe the solution you'd like**
If a fish is available in the area I am, and it is still missing in the specialization collecation from the End of Dragons new specialization, then display it. Maybe make an option to check in the settings for that.

ToDo, Achivement IDs for specialization collections

![SpecCollect-BlishHUD-Fishing-Buddy](https://user-images.githubusercontent.com/83425226/164989865-88c4d5cc-9d4e-4205-bcd6-d1bc2831d714.jpg)
.

**Comment by oeGStefan** [comment]
achivement id - achievement name
item id - fish name

--

6073 - Dichotomy
97329 - Albino Gourami

6093 - Quietus
95951 - Blue Dorado

6413 - Gravity
97794 - Unicorn Fish

6467 - Possession
96344 - Sturgeon

6167 - The Keenest Cut
97722 - Humphead Wrasse

6262 - Percussive Maintenance
95861 - Amber Trout

6495 - Purifier
97714 - Dragonet

6295 - Prima Donna
96443 - Giant Gourami

6337 - Crushing Weight
97604 - Stingray

**Comment by EclipseTech** [comment]
I've added these fish into notes. I'll add a way to display notes as well. 
Adding this to the TODO option selection for "Display Specialization Fish" (description: "Display uncaught fish from specialization achievements")

**Comment by EclipseTech** [comment]
There are other modules that help with other types achievement tracking. I'm closing this as it has a way to display in Fishing Buddy.
