### ISSUE TITLE
Displaying wrong time

### ISSUE THREAD

**Issue by codesmith47** [EclipseTech/FishingBuddy#28]
**Describe the bug**
The module is show the wrong time of day it is 00:01 CEST which should be nighttime in Tyria, but it shows as Daytime

**To Reproduce**
1. Go to Draconis Mons when it is day time in tyria
2. wait for nighttime.
3. See error

**Expected behavior**
Show correct time of day

**Screenshots**
![grafik](https://user-images.githubusercontent.com/88629925/197295284-79fd8f2b-8b68-4fa4-98ab-b82ddb327b7e.png)

**Module Info (please complete the following information):**
 - Module Version: 1.0.14
 - Include Logs: [blishhud.20221021-233049.log](https://github.com/EclipseTech/FishingBuddy/files/9842783/blishhud.20221021-233049.log)

**Additional context**
 - Map: Draconis Mons

**Comment by EclipseTech** [comment]
Draconis Mons is fixed to 09:00 tyrian time at all times.
https://wiki.guildwars2.com/wiki/Day_and_night#List_of_locations_with_day-night_cycle
