### ISSUE TITLE
Add info to fish.json

### ISSUE THREAD

**Issue by EclipseTech** [EclipseTech/FishingBuddy#5]
Add unchanging API data to fish.json
* Item Id
* Achievement Id
* Other?

**Comment by oeGStefan** [comment]
Can I provide an Excel file with the information and you are going to add it to the json?

**Comment by oeGStefan** [comment]
[fishing-buddy-fish-json-v2.txt](https://github.com/EclipseTech/FishingBuddy/files/8542463/fishing-buddy-fish-json-v2.txt)

I've done a txt version of that fish.json, that you may can just use.
I do not know, if the order of the elements within one dataset needs to be special.
I resorted for better readability. Just let me know, if that helps.

**Comment by EclipseTech** [comment]
Added v1.0.6
