### ISSUE TITLE
Fish display panel options

### ISSUE THREAD

**Issue by EclipseTech** [EclipseTech/FishingBuddy#9]
Build fish panel from different anchors

Currently fish icons populated from top left of panel and added left -> right (column by column) then top -> bottom (row by row).

Additional options to build right -> left or bottom -> top

Or possibly also let user choose # of rows/columns instead of calculating

**Comment by EclipseTech** [comment]
Display horizontal vs vertical as well

**Comment by SOL4RIS** [comment]
Just wanted to add that I would love to see this feature! I wanted to anchor to bottom/right to align to the left of my mini map, but the current default alignment doesn't allow for this.

**Comment by EclipseTech** [comment]
1.0.4 should address this with vertical / horizontal display & anchor / build direction
